const APP_VERSION = 'Manulife Assign V1-20210122'
const APP_PORT = 3000
const DATABASE_URL = 'mongodb://mongo:27017/manulife-assign'
const REPORT_HEADER_ARR = ['USER_NAME','AGE','HEIGHT','GENDER','SALE_AMOUNT','LAST_PURCHASE_DATE']

module.exports ={
    APP_VERSION, APP_PORT, DATABASE_URL, REPORT_HEADER_ARR
}